services:
  topolino-monitor:
    build: .
    container_name: topolino_monitor
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:8085:8085"
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
